import NativeBackupLib from '../lib/NativeBackupLib';

const NativeBackupConstants = () => {
  const {
    actionTypes: {
      LOG_IN,
      LOG_OUT,
      CREATE_BACKUP,
      CANCEL_ALL_BACKUP_TASKS,
      GET_NOTES_IMAGES_SIZE_IN_BYTES,
      GET_BACKUPS_LIST,
      REMOVE_BACKUP,
      RESTORE_FROM_BACKUP,
    },
    eventTypes: {
      LOG_IN_RESULT,
      LOG_OUT_RESULT,
      CREATE_BACKUP_RESULT,
      GET_NOTES_IMAGES_SIZE_IN_BYTES_RESULT,
      CREATE_BACKUP_PROGRESS_CHANGED,
      CREATE_BACKUP_FINISHED,
      CREATE_BACKUP_CANCELLED,
      CREATE_BACKUP_ERROR,
      GET_BACKUPS_LIST_RESULT,
      GET_BACKUPS_LIST_ERROR,
      REMOVE_BACKUP_FINISHED,
      REMOVE_BACKUP_ERROR,
      RESTORE_FROM_BACKUP_PROGRESS_CHANGED,
      RESTORE_FROM_BACKUP_FINISHED,
      RESTORE_FROM_BACKUP_CANCELLED,
      RESTORE_FROM_BACKUP_ERROR,
    },
    taskProgressTypes: {SIMPLE, COMPLEX},
    createBackupTaskStagesTypes: {
      PREPARING_DATA_STAGE,
      SAVING_APP_SETTINGS_STAGE,
      SAVING_NOTES_TEXT_STAGE,
      SAVING_NOTES_IMAGES_STAGE,
    },
    restoreFromBackupTaskStageTypes: {
      PREPARING_BACKUP_DATA_STAGE,
      RESTORING_APP_SETTINGS_STAGE,
      RESTORING_NOTES_TEXT_STAGE,
      RESTORING_NOTES_IMAGES_STAGE,
      FINISHING_STAGE,
    },
  } = NativeBackupLib.getConstants();

  return {
    actionTypes: {
      LOG_IN,
      LOG_OUT,
      CREATE_BACKUP,
      CANCEL_ALL_BACKUP_TASKS,
      GET_NOTES_IMAGES_SIZE_IN_BYTES,
      GET_BACKUPS_LIST,
      REMOVE_BACKUP,
      RESTORE_FROM_BACKUP,
    },
    eventTypes: {
      LOG_IN_RESULT,
      LOG_OUT_RESULT,
      CREATE_BACKUP_RESULT,
      GET_NOTES_IMAGES_SIZE_IN_BYTES_RESULT,
      CREATE_BACKUP_PROGRESS_CHANGED,
      CREATE_BACKUP_FINISHED,
      CREATE_BACKUP_CANCELLED,
      CREATE_BACKUP_ERROR,
      GET_BACKUPS_LIST_RESULT,
      GET_BACKUPS_LIST_ERROR,
      REMOVE_BACKUP_FINISHED,
      REMOVE_BACKUP_ERROR,
      RESTORE_FROM_BACKUP_PROGRESS_CHANGED,
      RESTORE_FROM_BACKUP_FINISHED,
      RESTORE_FROM_BACKUP_CANCELLED,
      RESTORE_FROM_BACKUP_ERROR,
    },
    taskProgressTypes: {SIMPLE, COMPLEX},
    createBackupTaskStagesTypes: {
      PREPARING_DATA_STAGE,
      SAVING_APP_SETTINGS_STAGE,
      SAVING_NOTES_TEXT_STAGE,
      SAVING_NOTES_IMAGES_STAGE,
    },
    restoreFromBackupTaskStagesTypes: {
      PREPARING_BACKUP_DATA_STAGE,
      RESTORING_APP_SETTINGS_STAGE,
      RESTORING_NOTES_TEXT_STAGE,
      RESTORING_NOTES_IMAGES_STAGE,
      FINISHING_STAGE,
    },
  };
};

export default NativeBackupConstants();
